services:
  # Backend API Service
  - type: web
    name: mp3converter-tiago-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    
  # Frontend Web Service
  - type: web
    name: tiago-mp3converter
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: mp3converter-tiago-api